kkkt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from home.views import (home, video_play,listing, single_church, leaders_view, 
feed_view, comments)
from home.views import SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    path('video',video_play, name='video'),
    path('listing/',listing, name='listing'),
    path('search/',SearchView.as_view(), name='search'),
    path('single/<int:id>/',single_church, name='single'),
    path('leaders/<int:id>/',leaders_view, name='leaders'),
    path('feeds/', feed_view, name='feeds'),
    path('feed-details/<int:id>/',comments, name='feed-details'),

] 

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

home/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.db.models import Manager as GeoManager
from django.contrib.auth.models import User
from django.utils import timezone
import math


class Platform(models.Model):
    users = models.ManyToManyField(User)
    dominion = models.CharField(max_length= 100, default= 'Lutheran')
    church_name = models.CharField(max_length=100, blank=True, null=True)
    region = models.CharField(max_length=100,blank=True, null=True)
    image = models.ImageField(upload_to='platform_image', blank=True, null=True)
    descriptions = models.TextField(blank=True, null=True)
    geom = models.PointField(blank=True, null=True)
    objects = GeoManager()

    def user_count(self):
        return self.users.count()
    

    def __str__(self):
        return self.church_name

class BannerVideo(models.Model):
    STATUS  = (
    ( 0 , 'Draft'),
    ( 1 ,  'Public')
    )
    name = models.CharField(max_length=100, blank=False, null=False)
    video = models.FileField(upload_to= "video" ,null = True, blank = True)
    status = models.IntegerField(choices=STATUS)
    create_on = models.DateTimeField(default= datetime.now)

    def __str__(self):
        return self.name

class Event(models.Model):

    EVENT_STATUS = (
            (0, 'NO'),
            (1,'YES')
        )

    is_live = models.BooleanField(choices=EVENT_STATUS,)
    title = models.CharField( max_length=120)
    event_date = models.DateTimeField(default= datetime.now)
    # venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    venue = models.CharField(max_length=255, blank=True, null=True)
    organiser = models.CharField(max_length=200,null=True,blank=True)
    description = models.TextField(blank=True)
    church = models.ManyToManyField(Platform)
    file = models.FileField(upload_to='files', null=True, blank=True)
    # slug = models.SlugField(max_length=200, unique=True)
    updated_on = models.DateTimeField(default= datetime.now)
    created_on = models.DateTimeField(default= datetime.now)
    attendees = models.ManyToManyField(User)
    # status = models.IntegerField(choices=ADVERTS_STATUS, default=0)

    def __str__(self):
        return self.title

class ChurchAdverts(models.Model):
    ADVERTS_STATUS = (
    (0, "Draft"),
    (1, "Publish")
    )
    church = models.ManyToManyField(Platform)
    title = models.CharField(max_length=200, unique=True)
    file = models.FileField(upload_to='files', null = True, blank=True)
    # slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=ADVERTS_STATUS, default=0)

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = 'ChurchAdverts'

    def __str__(self):
        return self.title

class Denomination(models.Model):
    it_belongs_to = models.ForeignKey(Platform, on_delete=models.CASCADE)
    denomination_name = models.CharField(max_length=100, null=True, blank=True)
    create_on = models.DateTimeField(default=datetime.now)
    users= models.ManyToManyField(User, null= True, blank= True)

    class Meta:
        verbose_name_plural = "Denomination"

    def __str__(self):
        return self.denomination_name

class PastorsDetails(models.Model):
    ChurchDetails = models.ForeignKey(Platform, on_delete=models.CASCADE)
    pastor_name = models.OneToOneField(User,null= True, blank = True, on_delete= models.CASCADE)
    class Meta:
        verbose_name_plural = "Pastor"
    def __str__(self):
        return self.pastor_name.username
    

class LeaderDetails(models.Model):
    LEADERSHIP_TREE = (
        ('Mchungaji Kiongozi','Mchungaji Kiongozi'),
        ('Mchungaji Msaidizi','Mchungaji Msaidizi'),
        ('Muinjilisti','Muinjilisti'),
        ('Mzee wa Kanisa','Mzee wa Kanisa'),
        ('Mzee wa kanisa/Mama','Mzee wa kanisa/Mama'),

    )
    a_leader_for = models.ForeignKey(Platform, on_delete=models.CASCADE)
    leader_name = models.ForeignKey( User, on_delete=models.CASCADE, null=True, blank=True)
    leader_title = models.CharField(max_length=255, choices=LEADERSHIP_TREE)
    class Meta:
        verbose_name_plural = "Leader "
    def __str__(self):
        return self.leader_title


class Feed_list(models.Model):
    STATUS = (
    (0, "Draft"),
    (1, "Publish")
    )
    posted_by = models.ForeignKey(Platform, on_delete= models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='feed_image', null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    status = models.IntegerField(choices=STATUS)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.posted_by} Church feed'

    def published(self):
        now = timezone.now()

        diff = now - self.updated
        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            seconds = diff.seconds
            if seconds == 1:
                return str(seconds) + " second ago"
            else:
                return str(seconds) + " seconds ago"
        
        if diff.days == 0 and diff.seconds >= 60 and diff.seconds < 3600:
            minutes = math.floor(diff.seconds/60)
            if minutes == 1:
                return str(minutes) + " minute ago"
            else:
                return str(minutes) + " minutes ago"
    
        if diff.days == 0 and diff.seconds >= 3600 and diff.seconds < 86400:
            hours = math.floor(diff.seconds/3600)
            if hours == 1:
                return str(hours) + " hour ago"
            else:
                return str(hours) + " hours ago"

        if diff.days >= 1 and diff.days < 30:
            days = diff.days
            if days == 1:
                return str(days) + " day ago"
            else:
                return str(days) + " days ago"
        
        if diff.days >= 30 and diff.days < 365:
            months = math.floor(diff.days/30)
            if months == 1:
                return str(months) + " month ago"
            else:
                return str(months) + " months ago"

        if diff.days >= 365:
            years = math.floor(diff/365)
            if years == 1:
                return str(years) + " year ago"
            else:
                return str(years) + " years ago"




class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Feed_list, on_delete=models.CASCADE)
    contents = models.TextField(max_length=100)
    # reply = models.ForeignKey('Comment', null=True, related_name='replies',on_delete=models.CASCADE)
    commented_on = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return str(self.user.username)

    




home/forms.py
from django import forms
from .models import Comment

class commentForm(forms.Form):
	contents = forms.CharField(widget=forms.TextInput(
	attrs={'class':'form-control','placeholder':'add comment here'}
	),label="Comment")

	class Meta:
		modal = Comment
		fields = ['contents']

home/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from .models import *
from django.views.generic import ListView
from django.db.models import Q
from django.core.serializers import serialize
import json
from django.http import HttpResponse,JsonResponse
from .forms import commentForm

# Create your views here.

# Create your views here.
def home(request):
    video = BannerVideo.objects.all()
    context = {
        'video':video
    }
    return render(request, 'home/home_page.html', context)

def video_play(request):
    video = BannerVideo.objects.all()
    context = {
        'video':video
    }
    return render(request, 'home/video_play.html', context)

def listing(request):
    data = Platform.objects.all()
    query = request.GET.get('q')
    if query:
        data = Platform.objects.filter(
            Q(church_name__icontains=query)|
            Q(descriptions__icontains=query)|
            Q(dominion__icontains=query)
        )
    context = {
        'data':data

    }
    return render(request, 'home/listing.html', context)

# def search(request):
#     query = request.GET.get('q')
#     if query:
#         plat = Platform.objects.filter(
#             Q(church_name=query),
#             Q(descriptions=query),
#         )
#     context = {
#         'plat':plat
#     }
#     return render(request, 'home/search.html', context)

class SearchView(ListView):
    model = Platform
    template_name ='home/search.html'
    context_object_name = 'data'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        if query:
            return Platform.objects.filter(
                Q(church_name__icontains=query) | Q(descriptions__icontains=query)
        )

def platfrom_data(request):
    platforms = serialize('geojson', Platform.objects.all())
    return JsonResponse(json.loads(platforms))

def single_church(request, id):
    data = Platform.objects.get(id=id)
    event = Event.objects.all()
    ads = ChurchAdverts.objects.all()
    denom = Denomination.objects.get(id=id)
    pastor = PastorsDetails.objects.get(id=id)
    context = {
        'data':data,
        'event':event,
        'ads':ads,
        'denom':denom,
        'pastor':pastor
    }
    return render(request, 'home/listing-single.html', context)

def leaders_view(request, id):
    leader = LeaderDetails.objects.get(id=id)
    data = Platform.objects.get(id=id)
    pastor = PastorsDetails.objects.get(id=id)
    denom = Denomination.objects.all()
    context = {
        'leader':leader,
        'data':data,
        'pastor':pastor,
        'denom':denom,
    }
    return render(request, 'home/leaders.html', context)

def feed_view(request):
    feed = Feed_list.objects.all().extra(select=
    {'comment_count':'SELECT count(contents) FROM home_comment WHERE home_comment.post_id=home_feed_list.id'},)
    context = {
        'feed':feed
    }
    return render(request, 'home/feeds.html',context )

def comments(request, id):
    feed = Feed_list.objects.get(id=id)
    comment = Comment.objects.filter(post=feed,).order_by('-id')
    if request.method == 'POST':
        form = commentForm(request.POST)

        if form.is_valid():
            contents = request.POST.get('contents')
            comment = Comment.objects.create(post=feed, contents=contents, user=request.user)
            comment.save()
            return redirect('feed-details',id=id)

    form = commentForm()
    context = {
        'feed':feed,
        'comments':comment,
        'form':form
    }
    return render(request, 'home/more.html', context)

templates/home/feeds.html
{% extends 'base.html'%}
{% load static%}
 
{% block title%}
<title>Church | feeds</title>
{% endblock title%}



{% block contents%}
<link type="text/css" rel="stylesheet" href="{% static 'home/css/reset.css'%}">
<link type="text/css" rel="stylesheet" href="{% static 'home/css/plugins.css'%}">
<link type="text/css" rel="stylesheet" href="{% static 'home/css/style.css'%}">
<link type="text/css" rel="stylesheet" href="{% static 'home/css/color.css'%}">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<div class="loader-wrap">
    <div class="pin"></div>
    <div class="pulse"></div>
</div>


!-- Main   -->
<div id="main">
    <!-- wrapper -->
    <div id="wrapper">
        <!--content -->
        <div class="content">
            <!--section -->
            <section id="sec1">
                <!-- container -->
                <div class="container">
                    <!-- profile-edit-wrap -->
                    <div class="profile-edit-wrap">
                        <div class="profile-edit-page-header">
                            {% if request.user%}
                            <h2>Karibu Sana {{user.username|capfirst}}</h2>
                            {% else%}
                            <h2>Karibu Sana</h2>
                            {% endif%}
                            <div class="breadcrumbs">
                                <a href="#">Home</a>
                                <a href="#">Dasboard</a>
                                <a href="{% url 'feeds' %}">Feed</a></div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                
                                <div class="fixed-bar fl-wrap">
                                    <div class="user-profile-menu-wrap fl-wrap">
                                        <!-- user-profile-menu-->
                                        <div class="user-profile-menu">
                                            <img src="{{data.image.url}}" alt="">
                                        </div>
                                        <!-- user-profile-menu end-->
                                        <!-- user-profile-menu-->
                                        <div class="user-profile-menu">
                                          <h1>{{ user.username}}</h1>
                                        </div>
                                        <!-- user-profile-menu end-->
                                        <!-- <a href="#" class="log-out-btn">Log Out</a> -->
                                    </div>
                                </div>
                                
                            </div>
                            
                            <div class="col-md-9" style="padding-left: 50px;">
                                {% for feed in feed %}
                                <div class="post" style=" border: 1px solid #97d5f1; box-shadow: 2px 2px 5px rgba(0,0,0,0.6); width: 650px; border-radius: 10px;">
                                    <br>
                                    <div class="row">
                                    <div class="col-md-3" style="margin-left: 20;">
                                        <div class="image">
                                            <img src="{{feed.posted_by.image.url}}" alt="image here" style="border-radius: 100px; width: 100px; height: 100px;">
                                        </div>
                                    </div>
                                    <div class="col-md-7">
                                        <br>
                                        <b><p style="text-align:left; font-weight: bolder; font-size: 20;">
                                            {{feed.posted_by}}</p></b>
                                        <b><p style="text-align:left; font-weight: bolder; font-size: 20;"> 
                                            {{feed.published}}</p></b>
                                    </div>
                                </div>
                                <br>
                                <div class="feedInfo" style="text-align: left; margin-left: 10px; ">
                                    {% if feed.description%}
                                    <p style="font-size: 18; margin: 0px 40px 0px 60px;" >{{feed.description}}</p>
                                    {% endif%}
                                     {% if feed.image%}
                                     <div class="feedimg" style="text-align: center;  margin-left: 0px; margin-right: 5px;">
                                        <img src="{{feed.image.url}}"" alt="" style="width:80%; border-radius: 5px;">
                                     </div>
                                     {% endif%}
                                     <br>
                                      <div class="links" style="display: inline-flex;">
                                        <a style="padding: 0px 0px 0px 100px;" href="{% url 'feed-details' feed.id%}">
                                            <b>{{feed.comment_count}} 
                                               <i class=" far fa-comment-alt"></i></b>
                                        </a>
                                        <a style="padding: 0px 0px 0px 100px;" href="{% url 'feed-details' feed.id%}">
                                            <b>{{feed.comment_count}} 
                                                <i style="color: red;" class="fa fa-heart"></i>
                                            </b>
                                        </a>
                                      </div>
                                </div>
                                <br>
                               
                            </div>
                            <br><br>
                            {% endfor%}
                        </div>
                        
                       
                    </div>
                    <!--profile-edit-wrap end -->
                </div>
                <!--container end -->
            </section>
            <!-- section end -->
            <div class="limit-box fl-wrap"></div>
            <!--section -->
            <section class="gradient-bg" style="height: 30px;">
                <div class="cirle-bg">
                    <div class="bg" data-bg="images/bg/circle.png"></div>
                </div>
                <div class="container">
                    <div class="join-wrap fl-wrap">
                        <div class="row">
                            <div class="col-md-8" style="line-height: 70px;">
                                <!-- <h3>Do You Have Questions ?</h3>
                                <p>Lorem ipsum dolor sit amet, harum dolor nec in, usu molestiae at no.</p>
                            </div>
                            <div class="col-md-4"><a href="contacts.html" class="join-wrap-btn">Get In Touch <i
                                        class="fa fa-envelope-o"></i></a></div> -->
                        </div>
                    </div>
                </div>
            </section>
            <!-- section end -->
        </div>
    </div>
    <!-- wrapper end -->
    <!--footer -->
    <!--footer end  -->
    <a class="to-top"><i class="fa fa-angle-up"></i></a>
</div>
<!-- Main end -->


<!--=============== scripts  ===============-->
<script type="text/javascript" src="{% static 'home/js/jquery.js'%}"></script>
<script type="text/javascript" src="{% static 'home/js/plugins.js'%}"></script>
<script type="text/javascript" src="{% static 'home/js/scripts.js'%}"></script>
<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?key=AIzaSyDwJSRi0zFjDemECmFl9JtRj1FY7TiTRRo"></script>
<script type="text/javascript" src="js/map-add.js"></script>
{%endblock contents%}

{% block footer%}
{%endblock footer%}

templates/home/leaders.html
{% extends 'base.html'%}
{% load static%}

{% block title%}
<title>Church | Profile</title>
{% endblock title%}

{% block contents%}
<!--=============== css  ===============-->
<link type="text/css" rel="stylesheet" href="{% static 'home/css/reset.css'%}">
<link type="text/css" rel="stylesheet" href="{% static 'home/css/plugins.css'%}">
<link type="text/css" rel="stylesheet" href="{% static 'home/css/style.css'%}">
<link type="text/css" rel="stylesheet" href="{% static 'home/css/color.css'%}">
<!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
<style>
    .mySlides {
        display: none;
    }
</style>
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
<!-- loader -->
<div class="loader-wrap">
    <div class="pin"></div>
    <div class="pulse"></div>
</div>
<!--  loader end -->
<!-- Main   -->
<div id="main">
    <!-- wrapper -->
    <div id="wrapper">
        <!--content -->
        <div class="content">
            <!--section -->
            <section id="sec1">
                <!-- container -->
                <div class="container">
                    <!-- profile-edit-wrap -->
                    <div class="profile-edit-wrap">
                        <div class="profile-edit-page-header">
                            {% if request.user%}
                            <h2>Karibu Sana {{user.username|capfirst}}</h2>
                            {% else%}
                            <h2>Karibu Sana</h2>
                            {% endif%}
                            <div class="breadcrumbs"><a href="#">Home</a><a href="#">Dasboard</a></div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">

                                <div class="fixed-bar fl-wrap">
                                    <div class="user-profile-menu-wrap fl-wrap">
                                        <!-- user-profile-menu-->
                                        <div class="user-profile-menu">
                                            <img src="{{data.image.url}}" alt="">
                                        </div>
                                        <!-- user-profile-menu end-->
                                        <!-- user-profile-menu-->
                                        <div class="user-profile-menu">
                                            <h3>{{data.church_name}}</h3>
                                            <ul>
                                                <li><a href="#"><i class="fa fa-th-list"></i>
                                                        Kiongozi: Mch {{pastor.pastor_name|capfirst}}</a></li>
                                                <li><a href="dashboard-bookings.html"><i class="fa fa-users ml-5"></i>
                                                        Member{{data.user_count|pluralize}}
                                                        <span class="mr-5"
                                                            style="margin-right: 10px;">{{data.user_count}}</span></a>
                                                </li>
                                                <li><a href="dashboard-review.html"><i class="fa fa-map-marker-alt"></i>
                                                        {{data.region}}</a></li>
                                                <li><a href="dashboard-add-listing.html">
                                                        <i class="fa fa-book"></i> Demomination{{denom.count|pluralize}}
                                                        <span class="mr-5"
                                                            style="margin-right: 10px;">{{data.denomination_set.all.count}}</span></a></li>
                                                <li><a href="dashboard-add-listing.html" class="user-profile-act">
                                                        <i class="fa fa-user"></i> Your Profile</a></li>
                                            </ul>
                                        </div>
                                        <!-- user-profile-menu end-->
                                        <!-- <a href="#" class="log-out-btn">Log Out</a> -->
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-9">
                               <div class="leaders-list" >
                                {% for leader in data.leaderdetails_set.all%}
                                    <div class="row">
                                      
                                        <div class="leader" style=" border-radius: 5px; height: 150px; border: 1px solid #a9def7; box-shadow: 2px 2px 5px rgba(0,0,0,0.6);">
                                            <div class="col-md-2">
                                                <div class="image" style="margin-top: 10px;">
                                                    <img style="border-radius: 100px; height: 120px;" src="{{data.image.url}}" alt="">
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <div class="" style="margin-top: 30px;">
                                                    <h4 style="text-align: left; text-indent: 10px;margin-bottom: 25px;"><b>{{leader.leader_name}}</b></h4 s>
                                                    <p style="text-align: left;text-indent: 10px;">{{leader.leader_title}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    
                                    </div>
                                    <br><br><br>
                                    {% endfor%}
                               </div>
                            </div>
                            </div>
                        </div>
                        <!--profile-edit-wrap end -->
                    </div>
                    <!--container end -->
            </section>
            <!-- section end -->
            <div class="limit-box fl-wrap"></div>
            <!--section -->
            <section class="gradient-bg" style="height: 30px;">
                <!-- <div class="cirle-bg">
                    <div class="bg" data-bg="images/bg/circle.png"></div> -->
                </div>
                <div class="container">
                    <div class="join-wrap fl-wrap">
                        <div class="row">
                            <div class="col-md-8" style="line-height: 70px;">
                                <!-- <h3>Do You Have Questions ?</h3>
                                <p>Lorem ipsum dolor sit amet, harum dolor nec in, usu molestiae at no.</p>
                            </div>
                            <div class="col-md-4"><a href="contacts.html" class="join-wrap-btn">Get In Touch <i
                                        class="fa fa-envelope-o"></i></a></div> -->
                            </div>
                        </div>
                    </div>
            </section>
            <!-- section end -->
        </div>
    </div>
    <!-- wrapper end -->
    <!--footer -->
    <!--footer end  -->
    <a class="to-top"><i class="fa fa-angle-up"></i></a>
</div>
<!-- Main end -->
<!--=============== scripts  ===============-->
<script type="text/javascript" src="{% static 'home/js/jquery.js'%}"></script>
<script type="text/javascript" src="{% static 'home/js/plugins.js'%}"></script>
<script type="text/javascript" src="{% static 'home/js/scripts.js'%}"></script>

{% endblock contents%}